# Set of functions for runing multiple compounds in batch mode

#' load chemical csv that can be used with batch mode
#' @description Load the chemical CSV file needed for batch mode processing 
#' The CSV file has the following column headers:
#' Name, 
#' Molecular Weight, 
#' LogP, 
#' LogKow,
#' Vapor Pressure,
#' Water Solubility,
#' Km,
#' Vmaxc,
#' Clintc,
#' IVIVE_type,
#' IVIVE_val1,
#' IVIVE_val2,
#' @param file_path full path to csv file
#' @export
loadBatchChemicalData <- function(file_path = NULL){
  chemdf <- data.frame(stringsAsFactors = F)
  if (is.null(file_path)){
    file_path <- file.choose()
  }
  chemdf <-read.csv(fpath,T,stringsAsFactors = F,skip = 1)
  batchfilecols <- colnames(chemdf)
 # print(batchfilecols)
  batchfilecols[3:8]<- c("mw","lkow","vpa","wsol","fupls","fresrp")
 # print(batchfilecols)
  colnames(chemdf)<- batchfilecols
  return(chemdf)
} 

#' load exposure csv that can be used with batch mode
#' @description Load the exposure CSV file needed for batch mode processing 
#' The CSV file has the following column headers:
#' Exposure Type, 
#' Exposure value 1,  
#' Exposure Value 2, 
#' Exposure Value 3,
#' Exposure Value 4,
#' Exposure Value 5
#' The values represent different parameters based on the type of exposure selected
#' Not all values are needed for each exposure type
#' For Bolus oral
#' 1. Bolus Dose in mg/kg
#' 2. number of bolus doses in a day
#' 3. Logical TRUE/FALSE for repeating bolus oral dose
#' @param file_path full path to csv file
#' @export
loadBatchExposureData <- function(file_path = NULL){
  expodf <- data.frame(stringsAsFactors = F)
  if (is.null(file_path)){
    file_path <- file.choose()
  }
  # read the csv file and return data to console
  return(expodf)
}

#' Run batch mode 
#' @description Runs simulations in batch mode. 
#' @param chemicals if load_files = True, string containing the path to chemical csv file
#' or a data frame as generated by \code{\link{loadBatchChemicalData}}
#' @param exposures if load_files = True, string containing the path to the exposure csv file
#' else a data frame as generated by \code{\link{loadBatchExposureData}}
#' @param load_files if TRUE, expects chemicals and exposures parameters to be strings containing full path to those files
#' else expects data frames
#' @param model Model against which all simulations are to be run 
#' defaults to rapidPBPK
#' @param organism Organism for which the model should be parameterised for all runs
#' defaults to human
#' @param save_to_file. If true promts the user to select a path to save a excel file with all the result
#' @return If save_to_file is FALSE, returns a list of dataframes, each contaning simulation results, indexed by compound name.
#' @export
runBatchMode <- function(chemicals =NULL, exposures =NULL, load_files = T,  
                         model = "rapidPBPK", vehicle = FALSE,
                         organism = "rat"){
  if (load_files == TRUE){
    chemdf <- loadBatchChemicalData(chemicals)
    #expodf <- loadBatchExposureData(exposures)
  }else{
    chemdf <- chemicals
    #expodf <- exposures
  }
  hpgl <- ifelse(organism == "human",99,110)
  mppgl <- ifelse(organism == "human",39.99,45)
  cppgl <- ifelse(organism == "human",80.7,91)
  mpcppgl <- list("MPPGL"=mppgl,"CPPGL"=cppgl)
  liver_wt <- ifelse(organism=="human",1.58,0.012)
  bw<- ifelse(organism=="human",81.21,0.023)
  num_chems <- nrow(chemdf)
  numchems <- nrow(chemdf)
  cpls_df <- data.frame()
  cmaxs <- list()
  aucs <- list()
  c_lasts <- list()
  metab_types<- list()
  expos <- list()
  fuplss <- list()
  fas<- list()
  for (i in 1:nrow(chemdf)){#nrow(chemdf)){
    chem_name <- chemdf[i,2]#){
    chem_params <- as.list(chemdf[i,3:6])
    #print(chem_params)
    partitions <- calculatePartitionCoefficients("one",chem_params,selected_org = organism)
   # print(partitions)
    metab_type <- tolower(chemdf[i,11])
    km <- chemdf[i,10]
    ka <- ifelse(is.na(chemdf[i,9]),5,chemdf[i,9])
    fupls <- ifelse(is.na(chemdf[i,7]),1,chemdf[i,7])
    if(is.na(km)){
      km <- 1
      km_flag <- F
      
    }else{
      km_flag <- T
    }
    #print(km_flag)
    mw <- chemdf[i,3]
    if(metab_type=="subcellular"){
      micl <- ifelse(is.na(chemdf[i,12]),0,chemdf[i,12])
      cycl <- ifelse(is.na(chemdf[i,13]),0,chemdf[i,13])
      scaled_hepcl <- calculateScaledSCClearance(c(micl,cycl),
                                                 c("ulmmP","ulmmP"),
                                                 org,liver_wt = liver_wt,
                                                 mpcppgl = mpcppgl,
                                                 km= ifelse(is.na(km),1,km),
                                                 return_total = T)
      vmaxc <- scaled_hepcl*km/(bw^0.75)
      vkm1c <- scaled_hepcl/liver_wt
    }else if(metab_type=="hepatocyte"){
      whcl <- chemdf[i,12]
      scaled_hepcl <- calculateScaledWholeHepClearance(whcl,"lhH",liver_wt,hpgl,
                                                       km = ifelse(is.na(km),1,km))
      vmaxc <- scaled_hepcl*km/(bw^0.75)
      vkm1c <- scaled_hepcl/liver_wt
    }else if(metab_type == "s9"){
      s9cl <- chemdf[i,12]
     # print(s9cl)
      scaled_hepcl <- calculateScaledS9Clearance(s9cl,"ulmmP",organism,liver_wt = liver_wt,
                                                 mpcppgl = mpcppgl)
      vmaxc <- scaled_hepcl*km/(bw^0.75)
      vkm1c <- scaled_hepcl/liver_wt
    }else{
      vmaxc <- chemdf[i,12]
      vkm1c<- chemdf[i,13]
    }
    if (!km_flag || is.na(vmaxc)){
      vmaxc <- 0
      }
    else{
      vkm1c <- 0
    }
    perfc <- 1
    if (organism == "human"){
      query <- "Select param,value From Physiological where physioid = 2;"
    }
    if (organism == "rat"){
      query <- "Select param,value From Physiological where physioid = 1;"
      
      #print(vals)
    }
    vals <- mainDbSelect(query)
    
    vals <- as.list(
      setNames(vals$value,nm = vals$param))
    
    vals[which(names(vals) %in% c("org","gender","cmplist"))]<- NULL
    vals <- lapply(vals,as.numeric)
    vals[names(partitions)]<- partitions
    #print(vals)
    # param_list <- c(vals,partitions,"vmaxc"=vmaxc,"vkm1c"=vkm1c,
    #                 "respr"=ventilation_rate,"tv"=tidal_volume,"ds"=ds,"gfr"=gfr,
    #                 "hct"=hct)
    initial_params <- within(as.list(vals),{
      mw <- mw
      km <- km
      vmaxc <- vmaxc
      vkm1c <- vkm1c
      total_vol <- vbldc+vfatc+vskinc+vmuscc+vbonec+vbrnc+vlngc+vhrtc+vkdnc+vgic+vlivc+vrpfc+vspfc
      #Scaled Tissue Volumes
      vbld <- vbldc*(perfc/total_vol)*bw     #L;Blood
      vpls <- vbld*(1-hct)
      vfat <- vfatc*(perfc/total_vol)*bw
      vskin <- vskinc*(perfc/total_vol)*bw
      vmusc <- vmuscc*(perfc/total_vol)*bw
      vbone <- vbonec*(perfc/total_vol)*bw
      vbrn <- vbrnc*(perfc/total_vol)*bw
      vlng <- vlngc*(perfc/total_vol)*bw
      vhrt <- vhrtc*(perfc/total_vol)*bw
      vkdn <- vkdnc*(perfc/total_vol)*bw
      vgi <- vgic*(perfc/total_vol)*bw
      vliv <- vlivc*(perfc/total_vol)*bw
      vrpf <- vrpfc*(perfc/total_vol)*bw
      vspf <- vspfc*(perfc/total_vol)*bw
      
      #Total Fractional Perfusion
      total_perf <- qfatc+qskinc+qmuscc+qbonec+qbrnc+qlngc+qhrtc+qkdnc+qvlivc+qrpfc+qspfc  # This does not include flow to GI since that is a part of liver venous flow
      
      #Scaled Perfusion
      qcp <- qcc*(1-hct)
      qfat <- qfatc*(1/total_perf)*qcp
      qskin <- qskinc*(1/total_perf)*qcp
      qmusc <- qmuscc*(1/total_perf)*qcp
      qbone <- qbonec*(1/total_perf)*qcp
      qbrn <- qbrnc*(1/total_perf)*qcp
      qlng <- qlngc*(1/total_perf)*qcp
      qhrt <- qhrtc*(1/total_perf)*qcp
      qkdn <- qkdnc*(1/total_perf)*qcp
      qvliv <- qvlivc*(1/total_perf)*qcp
      qgi <- (qgic/(qgic+qalivc))*qvliv
      qaliv <- (qalivc/(qgic+qalivc))*qvliv
      qrpf <- qrpfc*(1/total_perf)*qcp
      qspf <- qspfc*(1/total_perf)*qcp
      
      #Scaled tissue permeability coefs
      pafat <- 1000
      paskin <- 1000
      pamusc <- 1000
      pabone <- 1000
      pabrn <- 1000
      palng <- 1000
      pahrt <-1000
      pakdn <- 1000
      pagi <- 1000
      paliv <- 1000
      parpf <- 1000
      paspf <- 1000
      
      vkm1 <- vkm1c*vliv
      vmaxliv <- vmaxc*bw**0.75
      
      tstop <- 0
      tstart <- 0
      cinh <- 0
      qalv <- (tv-ds)*respr
      pair <- ifelse(pair >0,pair,1E-10)
      bdose <- 0
      blen <- 0
      breps <- 0
      totbreps<- 0
      drdose <- 0
      vdw <- 0
      dreps <- 0
      inhdose <- 0
      inhtlen <- 0
      inhdays <- 0
      ivdose <- 0
      ivlen <- 0
      fupls <- fupls
      ka <- ka
    })
    totdays <- chemdf[i,15]
    tstart <- 0
    initial_params["tstop"]<- tstop <- totdays*24
    initial_params["bdose"]<- bdose <- chemdf[i,14]
    #event times
    event_times <- seq(tstart,(tstop-0.0001),24)
    # var to change
    state_Var <- c("odose","totodose")
    
    # operation of event
    operation <- c("add","add")
    change_val1<- (bdose*bw*1000/mw)
    change_val2<- change_val1
    change_arr <- c(change_val1,change_val2)
    event_times <- c(tstart,tstart)
    eventDat <- data.frame(
      
      var = rep(x = state_Var,each = length(event_times)),
      time = rep(event_times,length(state_Var)),
      value = rep(x = change_arr,each = length(event_times)),
      method = rep(x = operation,each = length(event_times))
      
    )
    times <- seq(tstart,tstop,by=0.1)
    eventDat <- eventDat[order(eventDat$time),]
    state <- c(
      #exposure related
      inhswch=0,ainh=0,aexh=0,
      totodose=0,odose=0,odose1 = 0, odose2 = 0,
      totddose=0,ddose=0,ddose1 = 0, ddose2 = 0,
      aLAS= 0, akent = 0, afec = 0, aabsgut=0,
      ivswch=0,aiv=0,
      #compartments
      abld=0,
      abfat=0,atfat=0,
      abskin=0,atskin=0,
      abmusc=0,atmusc=0,
      abbone=0,atbone=0,
      abbrn=0,atbrn=0,
      ablng=0,atlng=0,
      abhrt=0,athrt=0,
      abgi=0,atgi=0,
      abliv=0,atliv=0,
      abkdn=0,atkdn=0,
      abrpf=0,atrpf=0,
      abspf=0,atspf=0,
      # Clearance
      ametliv1=0,ametliv2=0,aclbld=0,auexc=0,
      anabsgut=0,aucpls = 0)
    param_names <- getAllParamNames(model)
    initial_params <- initial_params[param_names]
    initial_params <- initial_params[-which(sapply(initial_params, is.null))]
    
    if(vehicle){
      initial_params["kfec"]<- chemdf[i,16]
      initial_params["kVtoL"]<- chemdf[i,17]
      initial_params["kent"]<- chemdf[i,18]
    }else{
      initial_params["fa"]<- chemdf[i,16]
    }
    initial_params["veh_flag"]<- 0
    print(c(initial_params$veh_flag,initial_params$bdose,initial_params$frwsol))
    initial_values <- list("evnt_times"= event_times,
                           "initial_params"= initial_params,
                           "times"=times,
                           "tstop"=tstop,
                           "tstart"=tstart,
                           "state"= state)
    #print(initial_values["initial_params"])
    result <- runFDPBPK(initial_values,model)
    res_df<- as.data.frame(result,stringsAsFactors = F)
    time <- res_df$pbpk.time
    if (ncol(cpls_df)== 0){
      cpls_df <- time
    }
    cpls <- res_df$pbpk.cpls
    #print(max(res_df$pbpk.totodose))
    auc <- res_df$pbpk.auc[length(res_df$pbpk.auc)]
    cpls_max <- max(cpls)
    c_last <- cpls[length(cpls)]
    cmaxs[[i]]<- cpls_max
    aucs[[i]]<- auc
    c_lasts[[i]]<- c_last
    metab_types[[i]]<- metab_type
    expos[[i]] <- bdose
    fuplss[[i]]<- fupls
    fas[[i]] <- chemdf[i,16]
    cpls_df <- cbind(cpls_df,cpls)
    #write.csv(res_df,paste0("E:/",chemdf[i,2],".csv"))

  }
  chem_names <- chemdf[2]
  colnames(chem_names)<- NULL
  #print(chem_names)
  #print(colnames(cpls_df))
  time_course_cols <- c("time",t(chem_names))
  #print(time_course_cols)
  colnames(cpls_df)<- time_course_cols
  write.csv(cpls_df,paste0(dirname(chemicals),"/Batch Mode Time course.csv"),
            row.names = F)
  results<- cbind(cmaxs,aucs,c_lasts,metab_types,expos,fuplss,fas)
  results <- cbind(as.vector(chem_names),results)
  results <- apply(results,2,as.character)
  colnames(results)<- c("Chemicals","Cmax","AUC24","Conc24",
                        "MetabolismTypes","Exposure",
                        "Fraction Unbound","Fraction absorbed")
  #print(results)
  write.csv(results,paste0(dirname(chemicals),"/Batch Mode Results.csv"))
  
}