# Set of functions for runing multiple compounds in batch mode

#' load chemical csv that can be used with batch mode
#' @description Load the chemical CSV file needed for batch mode processing 
#' The CSV file has the following column headers:
#' Name, 
#' Molecular Weight, 
#' LogP, 
#' LogKow,
#' Vapor Pressure,
#' Water Solubility,
#' Km,
#' Vmaxc,
#' Clintc,
#' IVIVE_type,
#' IVIVE_val1,
#' IVIVE_val2,
#' @param file_path full path to csv file
#' @export
loadBatchChemicalData <- function(file_path = NULL){
  chemdf <- data.frame(stringsAsFactors = F)
  if (is.null){
    file_path <- file.choose()
  }
  raw_data <- read.csv(file_path,T)
  return(chemdf)
} 

#' load exposure csv that can be used with batch mode
#' @description Load the exposure CSV file needed for batch mode processing 
#' The CSV file has the following column headers:
#' Exposure Type, 
#' Exposure value 1,  
#' Exposure Value 2, 
#' Exposure Value 3,
#' Exposure Value 4,
#' Exposure Value 5
#' The values represent different parameters based on the type of exposure selected
#' Not all values are needed for each exposure type
#' For Bolus oral
#' 1. Bolus Dose in mg/kg
#' 2. number of bolus doses in a day
#' 3. Logical TRUE/FALSE for repeating bolus oral dose
#' @param file_path full path to csv file
#' @export
loadBatchExposureData <- function(file_path = NULL){
  expodf <- data.frame(stringsAsFactors = F)
  if (is.null){
    file_path <- file.choose()
  }
  # read the csv file and return data to console
  return(expodf)
}

#' Run batch mode 
#' @description Runs simulations in batch mode. 
#' @param chemicals if load_files = True, string containing the path to chemical csv file
#' or a data frame as generated by \code{\link{loadBatchChemicalData}}
#' @param exposures if load_files = True, string containing the path to the exposure csv file
#' else a data frame as generated by \code{\link{loadBatchExposureData}}
#' @param load_files if TRUE, expects chemicals and exposures parameters to be strings containing full path to those files
#' else expects data frames
#' @param model Model against which all simulations are to be run 
#' defaults to rapidPBPK
#' @param organism Organism for which the model should be parameterised for all runs
#' defaults to human
#' @param save_to_file. If true promts the user to select a path to save a excel file with all the result
#' @return If save_to_file is FALSE, returns a list of dataframes, each contaning simulation results, indexed by compound name.
#' @export
runBatchMode <- function(chemicals =NULL, exposures =NULL, load_files = F,  model = "rapidPBPK", organism = "human"){
  # load chemical data
  # perform QSAR for Partition Coefficiant prediction
  # perfrom IVIVE based on input data
  # combine data to create a initial
}